import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/page";
import SmoothScroll from "./_components/Scroll Component/page";
import { Toaster } from "sonner";
import MySessionProvider from "./MySessionProvider/MySessionProvider";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { CartContextProvider } from "../context/cartitemContext";
import { WishlistProvider } from "../context/wishlistContext"; 
import Footer from "./_components/Footer/page"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MySessionProvider>
          <SmoothScroll />
          <CartContextProvider>
            <WishlistProvider> {/* ✅ هنا لفينا بالـ WishlistProvider */}
              <Navbar />
              {children}
              <Footer />
            </WishlistProvider>
          </CartContextProvider>

          <Toaster
            position="top-right"
            richColors
            closeButton
            toastOptions={{
              classNames: {
                toast: "rounded-xl shadow-lg border border-gray-200",
                title: "font-semibold text-base",
                description: "text-sm text-gray-500",
                success:
                  "bg-gradient-to-r from-green-500 to-emerald-600 text-white",
                error: "bg-gradient-to-r from-red-500 to-pink-600 text-white",
                warning:
                  "bg-gradient-to-r from-yellow-400 to-orange-500 text-black",
              },
            }}
          />
        </MySessionProvider>
      </body>
    </html>
  );
}
